### ISSUE TITLE
Chart does not compile while specifying apiKeyExistingSecret

### ISSUE THREAD

**Issue by istrau2** [DataDog/helm-charts#832]
failed exit status 1: Error: template: datadog/templates/NOTES.txt:1:56: executing "datadog/templates/NOTES.txt" at <eq .Values.datadog.apiKey "<DATADOG_API_KEY>">: error calling eq: incompatible types for comparison Use --debug flag to render out invalid YAML

**Describe what happened:**
Chart does not compile using 3.5.1

probably as a result of commented of having update apiKey to be nil by default here:
https://github.com/spencergilbert/helm-charts/commit/8185d54e8f5b44f17aac8b758bb0a3de112e828e
